import localFont from "next/font/local";
import "./globals.css";
import LayoutWrapper from "./components/LayoutWrapper/page"; // Componente Client separado
import { SidebarProvider } from "./components/SidebarContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Supervisor",
  description: "Generated by Unitec Sistemas.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
                <SidebarProvider>

        <LayoutWrapper>{children}</LayoutWrapper>
        </SidebarProvider>

      </body>
    </html>
  );
}
